CHANGELOG.md
assets/controllers/sprint-report_controller.js
src/Controller/SprintReportController.php
templates/sprint_report/index.html.twig

https://jira.itkdev.dk/browse/JE-387
Fixed budget path.

JE-387: Fixed budget path

---

CHANGELOG.md
src/Repository/WorklogRepository.php
templates/invoice_entry/edit.html.twig
templates/invoice_entry/new.html.twig
translations/messages.da.yaml

https://jira.itkdev.dk/browse/JE-387
* Added help text to invoice entry (worklog) type.
* Changed add worklogs button style.
* Fixed filter function for worklogs.

JE-387: Fixed issues with invoice entry

---

CHANGELOG.md
assets/controllers/worklog-select_controller.js
src/Controller/InvoiceEntryWorklogController.php
templates/invoice_entry/worklogs.html.twig

https://jira.itkdev.dk/browse/JE-387
Fixed path issue with worklog select.
Only submit values for checkboxes that are dirty.

JE-387: Fixed path issue with worklog select

---

CHANGELOG.md
composer.lock
docker-compose.dev.yml
docker-compose.override.yml
docker-compose.yml
src/Controller/CreateProjectController.php
src/Service/JiraApiService.php

https://jira.itkdev.dk/browse/JE-390
- Updated docker-compose files
- Updated bundles

JE-390: Updated docker-compose files. Updated bundles

---

CHANGELOG.md
src/Command/CalculateSumsCommand.php
src/Controller/InvoiceEntryController.php
src/Form/InvoiceType.php
templates/invoice_entry/worklogs.html.twig
templates/invoices/edit.html.twig
templates/invoices/index.html.twig
templates/project_billing/index.html.twig
translations/messages.da.yaml

- Changed redirect after create a manual invoice entry.
- Removed export options when client is not set.
- Added create new buttons to top of invoices and project billing lists.
- Added command to recalculate sums for all invoices.

JE-400: Minor UI fixes

---

CHANGELOG.md
assets/controllers/worklog-select_controller.js

Fixed select all on worklog list

JE-400: Fixed select all on worklog list

---

CHANGELOG.md
src/Service/JiraApiService.php

Fixed issue with issue version sync

JE-400: Fixed issue with issue version sync

---

CHANGELOG.md
assets/controllers/choices_controller.js
src/Controller/InvoiceController.php
src/Controller/InvoiceEntryWorklogController.php
src/Form/InvoiceEntryWorklogFilterType.php
src/Model/Invoices/InvoiceEntryWorklogsFilterData.php
src/Repository/IssueRepository.php
src/Repository/WorklogRepository.php
templates/invoice_entry/worklogs.html.twig
templates/invoices/edit.html.twig
templates/invoices/new.html.twig

Added choices.js to dropdowns with many options

JE-400: Added choices.js to dropdowns with many options

---

CHANGELOG.md
src/Model/Invoices/PagedResult.php
src/Service/ApiServiceInterface.php
src/Service/BillingService.php
src/Service/JiraApiService.php

JE-400: Optimized sync memory usage

---

CHANGELOG.md
src/Controller/InvoiceController.php
templates/invoices/edit.html.twig

JE-400: Added total amount to invoice

---

CHANGELOG.md
config/packages/twig.yaml
templates/invoice_entry/worklogs.html.twig
templates/invoice_entry/worklogs_show.html.twig
templates/invoices/index.html.twig
templates/project/index.html.twig
templates/project_billing/index.html.twig

Aligned date formats to danish order

JE-400: Aligned date formats

---

CHANGELOG.md
config/packages/framework.yaml
config/services.yaml

- adding x-api-key to headers for leantime api
- Defining Lean as projecttrackerinterface
N/A

Hotfix: Adding leantime api header + projecttrackerinterface definition

---

CHANGELOG.md
config/packages/framework.yaml

N/A
Adds header definition for leantime api calls to work. 
N/A

Hotfix: added header definition for leantime api calls

---

.env
CHANGELOG.md
composer.json
composer.lock
migrations/Version20231216075143.php

JE-400: Composer update

---

CHANGELOG.md
src/Service/LeantimeApiService.php

N/A
Undoes a couple of fixes for the leantime api integration, post stg degrade.
N/A

Hotfix: Corrected some leantime api calls

---

CHANGELOG.md
assets/controllers/navigation_controller.js
assets/styles/app.css
templates/components/navigation.html.twig
translations/messages.da.yaml

https://leantime.itkdev.dk/tickets/showAll?search=true&projectId=37&users=3&sprint=21&tab=ticketdetails#/tickets/showTicket/589
Introduces a way to create nested menus, and furthermore highlights the current page in the menu.

Feature/589: collapsible menu type, highlight current page

---

CHANGELOG.md
src/Controller/InvoiceController.php
src/Controller/InvoiceEntryController.php
src/Controller/ProjectBillingController.php
src/Form/InvoiceNewType.php
src/Form/ProjectBillingType.php
src/Repository/ProjectRepository.php
src/Security/Voter/AccessVoter.php

https://leantime.itkdev.dk/#/tickets/showTicket/566
* Adds a security voter for handling access to Invoice, InvoiceEntry and ProjectBilling.

Feature: Security voter

---

README.md

#566: Added to readme

---

CHANGELOG.md
assets/controllers/navigation_controller.js
assets/controllers/view-selector_controller.js

https://leantime.itkdev.dk/#/tickets/showTicket/585
Removed static from stimulus controller functions

Removed static from stimulus controller functions

---

CHANGELOG.md
composer.json
composer.lock
src/Controller/ManagementReportController.php
src/Controller/TeamReportController.php
src/Controller/ViewController.php
src/Form/ViewAddType.php
src/Form/ViewEditType.php
src/Repository/ViewRepository.php
src/Repository/WorklogRepository.php
src/Service/ManagementReportService.php
src/Service/TeamReportService.php
src/Service/ViewService.php
templates/management-report/create.html.twig
templates/management-report/output.html.twig
templates/reports/index.html.twig
templates/team-report/create.html.twig
templates/team-report/output.html.twig
templates/view/add.html.twig
templates/view/display.html.twig
templates/view/edit.html.twig
translations/messages.da.yaml

https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/399
- Add team report
- Add team report export
- Apply views to team reports
- Add open spout extension
- Add choices to views

Add team report

---

CHANGELOG.md
templates/account/edit.html.twig
templates/account/index.html.twig
templates/client/edit.html.twig
templates/client/index.html.twig
templates/home/index.html.twig
templates/invoice_entry/worklogs.html.twig
templates/invoice_entry/worklogs_show.html.twig
templates/invoices/edit.html.twig
templates/invoices/index.html.twig
templates/invoices/record.html.twig
templates/management-report/output.html.twig
templates/planning/planning-sprints.html.twig
templates/planning/planning-weeks.html.twig
templates/project/index.html.twig
templates/project_billing/index.html.twig
templates/project_billing/record.html.twig
templates/team-report/output.html.twig
templates/user/index.html.twig
templates/view/display.html.twig
templates/view/list.html.twig
templates/view/viewDataTableDisplay.html.twig

https://leantime.itkdev.dk/#/tickets/showTicket/932
Applies Twig coding standards by
* Cleaning up whitespace – or lack of it
* snake_casing camelCased variable names
Before:
After:

932: Cleaned up Twig templates

---

src/Repository/IssueRepository.php
src/Service/ProjectBillingService.php

https://leantime.itkdev.dk/#/tickets/showTicket/999
Updates handling of invoices and worklogs in project billing.

Release 2.0.0 fixes

---

.env
CHANGELOG.md
config/services.yaml
src/Controller/ClientController.php
src/Controller/InvoiceEntryController.php
templates/client/index.html.twig
translations/messages.da.yaml

https://leantime.itkdev.dk/#/tickets/showTicket/973
Updated standard price on clients.

973: Updated standard price on clients

---

CHANGELOG.md
README.md
composer.json
src/Service/BillingService.php
src/Service/DanishHolidayHelper.php
templates/invoices/edit.html.twig
tests/Service/DanishHolidayHelperTest.php
translations/messages.da.yaml

https://leantime.itkdev.dk/#/tickets/showTicket/972
Updates values in external invoice header as per https://leantime.itkdev.dk/#/tickets/showTicket/972

972: External invoicing

---

CHANGELOG.md
src/Service/DanishHolidayHelper.php
tests/Service/DanishHolidayHelperTest.php

https://leantime.itkdev.dk/#/tickets/showTicket/972
Updated holiday helper to handle more dates and – hopefully – do it correctly.

972: Updated bank holiday helper

---

.github/workflows/pr.yml
.gitignore
CHANGELOG.md
composer.json
composer.lock
symfony.lock
templates/_partials.html.twig
templates/components/icons.html.twig
templates/planning/planning-sprints.html.twig
templates/planning/planning-weeks.html.twig
templates/product/_delete_form.html.twig
templates/view/viewDelete.html.twig

Please add a link to the ticket being addressed by this change.
Replaces https://github.com/friendsoftwig/twigcs with https://github.com/VincentLanglet/Twig-CS-Fixer and applies Twig coding standards.
Note: The changes in `templates/` only affect whitespace (cf. https://github.com/itk-dev/economics/pull/97/files?diff=split&w=1).

Twig CS Fixer

---

CHANGELOG.md
src/Service/LeantimeApiService.php

https://leantime.itkdev.dk/#/tickets/showTicket/1111
Adds missing parameters in Leantime API call.

1111: Fixed fetching timesheet data from Leantime

---

CHANGELOG.md

Release 2.1.1

---

CHANGELOG.md
src/Service/BillingService.php

https://leantime.itkdev.dk/#/tickets/showTicket/1157
* Updates some values in export (columns Y and Z)
* Adds helper function to set cell value

1157: Updated external billing export

---

CHANGELOG.md
src/Controller/ProjectController.php
src/Service/LeantimeApiService.php

https://leantime.itkdev.dk/#/tickets/showTicket/1174
Fixes datetime format in Leantine API calls.

1174: Fixed datetime format in Leantime API calls

---

CHANGELOG.md
assets/styles/app.css
src/Form/InvoiceFilterType.php
src/Model/Invoices/InvoiceFilterData.php
src/Repository/InvoiceRepository.php
templates/invoices/index.html.twig
translations/messages.da.yaml

https://leantime.itkdev.dk/#/tickets/showTicket/1207
Adds free form search query on invoices (`/admin/invoices/`).

1207: Added invoice query

---

CHANGELOG.md
assets/styles/app.css
migrations/Version20240419120317.php
src/Controller/InvoiceController.php
src/Controller/ProjectBillingController.php
src/Entity/Invoice.php
src/Form/InvoiceFilterType.php
src/Form/InvoiceRecordType.php
src/Form/ProjectBillingRecordType.php
src/Model/Invoices/ConfirmData.php
src/Model/Invoices/InvoiceFilterData.php
src/Repository/InvoiceRepository.php
src/Service/BillingService.php
src/Service/ProjectBillingService.php
templates/invoices/index.html.twig
translations/messages.da.yaml

https://leantime.itkdev.dk/#/tickets/showTicket/1209
Adds “No cost” on invoices.

1209: No cost invoices

---

.docker/data/.gitignore
.docker/nginx.conf
.docker/templates/default.conf.template
CHANGELOG.md
docker-compose.dev.yml
docker-compose.redirect.yml
docker-compose.server.yml
docker-compose.yml
src/Repository/WorklogRepository.php

<https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/1213>
Makes "Periode til" inclusive, i.e. include worklogs on the selected date.
As an added bonus, the `docker compose` setup is also updated.

Worklog period filter

---

CHANGELOG.md
migrations/Version20240521135612.php
src/Entity/IssueProduct.php
src/Form/IssueProductType.php

<https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/1485>
Makes product quantity a float.

1485: Made product quantity floatable

---

CHANGELOG.md
migrations/Version20240530115938.php
src/Entity/InvoiceEntry.php
src/Entity/IssueProduct.php
src/Service/BillingService.php
src/Service/ProjectBillingService.php

<https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/1544>
Allows invoicing issues with products and no worklogs.

1544: Allowed invoicing issues with not worklogs

---

.env
.env.test
CHANGELOG.md
config/services.yaml
src/Controller/InvoiceController.php
src/Controller/InvoiceEntryController.php
src/Service/InvoiceEntryHelper.php
src/Service/ProjectBillingService.php
templates/invoices/edit.html.twig

<https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/1547>
Makes account definitions more general and sets account based on issue type.

1547: Set account based on invoice entry type

---

CHANGELOG.md
migrations/Version20240531125801.php
src/Service/ProjectBillingService.php

<https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/1590>
Adds worklog product as prefix on product invoice entries. A clever SQL query is used to update (some) existing entries.

1590: Added worklog product as prefix on product invoice entries

---

.github/workflows/pr.yml

Fixed docker service stuff

---

CHANGELOG.md
migrations/Version20240620091523.php
src/Entity/Worker.php
src/Model/Invoices/IssueData.php
src/Service/DataSynchronizationService.php
src/Service/LeantimeApiService.php

https://leantime.itkdev.dk/#/tickets/showTicket/1742
Fixed synchronization issues

Fixed synchronization issues

---

CHANGELOG.md
src/DataFixtures/AppFixtures.php
src/Service/HourReportService.php
templates/reports/hour_report.html.twig
translations/messages.da.yaml

https://leantime.itkdev.dk/#/tickets/showTicket/1812
Correct translation and added dueDate fixture data

1812: Hour report improvements

---

CHANGELOG.md
templates/invoice_entry/worklogs.html.twig

https://leantime.itkdev.dk/#/tickets/showTicket/1768
Added link to invoice entry that binds worklog

1768: Added link to invoice entry that binds worklog

---

CHANGELOG.md
migrations/Version20240708140922.php
src/Entity/Issue.php
src/Entity/Project.php
src/Entity/Version.php
src/Entity/Worklog.php
src/Service/DataSynchronizationService.php

- **Added data provider to all findOneBys**
- **1890: Added unique constraints**
<https://leantime.itkdev.dk/dashboard/show#/tickets/showTicket/1907>
* Adds condition on data provider on all `findOneBy` queries during data fetching.
* Adds unique constraints wherever it makes sense.
**IMPORTANT**: Before updating, i.e. running migrations, some data clean up must be performed:
```sql
-- Delete versions from project with only version references.
DELETE FROM version WHERE project_id NOT IN
(
SELECT -1
UNION SELECT project_id FROM project_client
UNION SELECT project_id FROM product
UNION SELECT project_id FROM invoice
UNION SELECT project_id FROM view_project
UNION SELECT project_id FROM worklog
UNION SELECT project_id FROM project_billing
UNION SELECT project_id FROM issue
)
;
-- Delete …
```

Data provider stuff

---

CHANGELOG.md
src/Controller/InvoiceEntryWorklogController.php
src/Controller/ProjectController.php
src/Form/InvoiceEntryWorklogFilterType.php
src/Form/ProjectFilterType.php
src/Model/Invoices/ProjectFilterData.php
src/Repository/ProjectRepository.php
templates/project/index.html.twig
translations/messages.da.yaml

https://leantime.itkdev.dk/?tab=ticketdetails#/tickets/showTicket/2031
When entering the project overview page, preset "included" filter and only load included projects, before filters are applied.

2031: Project overview standard settings

---

CHANGELOG.md
src/Repository/WorklogRepository.php
src/Service/DataProviderService.php
src/Service/DateTimeHelper.php
src/Service/LeantimeApiService.php
src/Service/WorkloadReportService.php
tests/Service/DateTimeHelperTest.php
tests/Service/WorkloadReportServiceTest.php

https://leantime.itkdev.dk/#/tickets/showTicket/2059
Since the number of working days varies from month to month and year to year, a more specific definition of said days need to be defined.
N/A

2059: Specify workload report week definition

---

CHANGELOG.md
src/Controller/InvoiceEntryWorklogController.php
src/Controller/ProjectController.php
src/Form/InvoiceEntryWorklogFilterType.php
src/Form/ProjectFilterType.php
src/Model/Invoices/ProjectFilterData.php
src/Model/Planning/Weeks.php
src/Repository/ProjectRepository.php
src/Service/LeantimeApiService.php
src/Service/PlanningService.php
templates/planning/projects.html.twig
templates/planning/users.html.twig
templates/project/index.html.twig
translations/messages.da.yaml

https://leantime.itkdev.dk/#/tickets/showTicket/2034
When selecting a period from and period to for an invoice, this date span should apply to the search performed when adding worklogs to an invoice entry.
N/A

2034: Invoice date select continuity

---

CHANGELOG.md

Release 2.4.1

---

CHANGELOG.md
src/Service/BillingService.php

https://leantime.itkdev.dk/#/tickets/showTicket/2265
Changed X column in external exported csv.

2265: Changed X column in external exported csv

---

CHANGELOG.md
migrations/Version20240906102815.php
src/Entity/Worker.php
src/Form/WorkerType.php
src/Service/PlanningService.php
templates/worker/index.html.twig
translations/messages.da.yaml

https://leantime.itkdev.dk/#/tickets/showTicket/2294
* Add worker name.

2294: Added worker name

---

CHANGELOG.md
package-lock.json

Npm audit fixes

---

CHANGELOG.md
src/Controller/PlanningController.php
src/Form/InvoiceFilterType.php
src/Repository/ProjectRepository.php
src/Service/PlanningService.php
templates/components/navigation.html.twig
templates/planning/planning.html.twig
translations/messages.da.yaml

* Fixed isBillable filter for project list.
* Removed unused code from planning overviews.

Planning cleanup and project.isBillable filter fix

---

CHANGELOG.md
src/Service/PlanningService.php

https://leantime.itkdev.dk/#/tickets/showTicket/2454
Hiding done tasks in planning overview
N/A

2454: Update done tasks check to use new enum in PlanningOverview

---

CHANGELOG.md
src/Service/WorkloadReportService.php
templates/reports/workload_report.html.twig

[2499](https://leantime.itkdev.dk/#/tickets/showTicket/2499)
Add worker name in workload report
N/A

2499: Worker name in Workload Report

---

CHANGELOG.md
src/Service/WorkloadReportService.php
tests/Service/WorkloadReportServiceTest.php

https://leantime.itkdev.dk/#/tickets/showTicket/2545
Fixed calculation to look at all worklogs for the year and expected workload instead of averaging over averages.

2545: Fixed average percentage calculation

---

CHANGELOG.md
templates/issue/index.html.twig
templates/issue/show.html.twig
templates/project_billing/edit.html.twig

Fixed status enum twig rendering.

Fixed status enum twig rendering

---

CHANGELOG.md

Release 2.5.1

---

CHANGELOG.md
src/Service/WorkloadReportService.php

Please add a link to the ticket being addressed by this change.
Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

3624: Fix workload report total average

---

.github/workflows/pr.yml
CHANGELOG.md
composer.json
composer.lock
docker-compose.override.yml
docker-compose.server.override.yaml
docker-compose.server.yml
docker-compose.yml

Upgraded to php 8.3 and node 20.

2299: Upgraded to php 8.3 and node 20

---

.eslintrc
.github/workflows/pr.yml
CHANGELOG.md
assets/controllers/action-button_controller.js
assets/controllers/planning-scroll_controller.js
assets/controllers/subscribe-button_controller.js
assets/controllers/sync-status_controller.js
assets/helpers/postRequestHandler.js
package-lock.json
package.json

2299: Fixed coding standards issues

---

CHANGELOG.md
src/Controller/HomeController.php
src/Model/DashboardData.php
src/Service/DashboardService.php
templates/home/card.html.twig
templates/home/index.html.twig
translations/messages.da.yaml

https://leantime.itkdev.dk/?tab=ticketdetails#/tickets/showTicket/3660
Adds a user dashboard.

User dashboard

---

CHANGELOG.md
assets/controllers/sync-id_controller.js
assets/controllers/sync_controller.js
src/Controller/PlanningController.php
src/Controller/SubscriptionController.php
src/Controller/SynchronizationJobController.php
templates/components/navigation.html.twig
templates/planning/planning.html.twig
translations/messages.da.yaml

Added project sync for planning view.

Added project sync for planning view

---

CHANGELOG.md
src/Service/SubscriptionHandlerService.php

N/A
Updating lastSent on subscription when mail has been sent.
N/A

Hotfix: Update subscription lastSent

---

.env
CHANGELOG.md
composer.json
composer.lock
config/packages/doctrine.yaml
src/Repository/WorklogRepository.php
src/Service/DashboardService.php
src/Service/DateTimeHelper.php

N/A
Refactor dashboard calculations to do SUM in database and limit to days in current year
- Let the database do `GROUP BY` and ´SUM`
- Exclude future dates and dates in previous year from norm time calculations

Refactor dashboard calculations to do SUM in database and limit to days in current year

---

.woodpecker/prod_economics.yml
.woodpecker/prod_itk_economics.yml
CHANGELOG.md

https://leantime.itkdev.dk/tickets/showKanban#/tickets/showTicket/4125
Setup auto deploy (woodpecker) for both prod sites

4125: Setup auto deploy (woodpecker) for both prod sites

---

CHANGELOG.md

Release 2.8.5

---

CHANGELOG.md
src/Service/LeantimeApiService.php

n/a anna just requested faster links
switched showkanban link with error link

remove showKanban stuff from link to leantime

---

CHANGELOG.md
src/Command/QueueSyncCommand.php

N/A
Change sync cron interval from every hour to once every midnight.
🖼️

Hotfix: Change sync cron interval

---

CHANGELOG.md
composer.json
composer.lock
docker-compose.server.override.yml
symfony.lock
templates/account/index.html.twig
templates/client/index.html.twig
templates/group/index.html.twig
templates/home/index.html.twig
templates/invoices/index.html.twig
templates/project_billing/index.html.twig
templates/reports/reports.html.twig

[#4823](https://leantime.itkdev.dk/#/tickets/showTicket/4823)
Economics runs out of memory during LT-sync.
This PR provides an immediate solution to the problem.
The linked ticket serves as base for a more solid long term solution. Work on that will begin soon.
This PR also came to include some composer related stuff, that came up in actions when i made the PR. Also the result of updated twig coding standards.
N/A

Hotfix: Up memory limit for LT sync

---

.github/workflows/pr.yml

https://leantime.itkdev.dk/#/tickets/showTicket/5490
Removed actions duplicates

5490: Removed actions duplicates
