- CHANGELOG.md
- config/packages/monolog.yaml
https://jira.itkdev.dk/browse/JE-403
Changed monolog config to ignore deprecations.
> JE-403: Removed deprecations from logging

- CHANGELOG.md
- src/Service/LeantimeApiService.php
https://leantime.itkdev.dk/#/tickets/showTicket/181
Changed how errors are handled in leantime api calls
> #181: Changed how errors are handled in leantime api calls

- CHANGELOG.md
- src/Form/InvoiceNewType.php
- templates/project/index.html.twig
- translations/messages.da.yaml
https://leantime.itkdev.dk/tickets/showAll?search=true&projectId=37&users=3&sprint=21&tab=ticketdetails#/tickets/showTicket/588
It should be visible what dataprovider belongs to a given project. Both in the project list and in the dropdown with projects that is available when creating a new invoice.
N/A
> Feature/588: project-dataprovider visibility

- CHANGELOG.md
- src/Service/LeantimeApiService.php
https://leantime.itkdev.dk/#/tickets/showTicket/935
- 932: Passed dates on to API
- 932; Removed superfluous filter
**Note**: Depends on changes from https://github.com/Leantime/leantime/pull/2398 in Leantime.
> Leantime API requests

- CHANGELOG.md
- src/Controller/ClientController.php
- src/Form/ClientType.php
- templates/client/index.html.twig
- translations/messages.da.yaml
https://leantime.itkdev.dk/#tickets/showTicket/973
Makes standard price optional on client in the UI. If a price on a client is not set, the globally defined price will be used.
> 973: Made price on client optional

- CHANGELOG.md
- src/Service/DataSynchronizationService.php
https://leantime.itkdev.dk/#/tickets/showTicket/1169
* Clears versions on Leantime issue before adding a new version. Leantime supports only one version (milestone) per issue.
* Fixes pagination issue. The Leantime API does not yet support pagination.
> 1169: Made sure that Leantime issues have at most one version (milestone)

- CHANGELOG.md
- migrations/Version20240418085604.php
- src/Entity/Worklog.php
- src/Service/DataSynchronizationService.php
https://leantime.itkdev.dk/#/tickets/showTicket/1202
Handles deleting of project worklogs that are removed in data provider source. Worklogs are soft-deleted so that we have a log of what has been deleted (mostly to satisfy our curiosity).
The check for which project worklogs to delete (https://github.com/itk-dev/economics/pull/106/files#diff-1e5cb9ea1ca2f6886be7660680b3504ab17245b4f872fbb4439fde8f841ef355R289-R302) may need further refinement.
For testing, this command can be used:
```shell
itkdev-docker-compose bin/console app:sync-worklogs -vvv && $(itkdev-docker-compose sql:connect) --table <<< "SELECT id, worklog_id, issue_id, deleted_at FROM worklog WHERE project_id = 362 ORDER BY worklog_id"
```
> 1202: Handled worklog deletions

- CHANGELOG.md
- src/Repository/InvoiceRepository.php
- templates/invoices/index.html.twig
- translations/messages.da.yaml
https://leantime.itkdev.dk/#/tickets/showTicket/1208
Changes default sorting of recorded invoices from “exported at” to “recorded at” ("bogført”).
> 1208: Changed default sorting of recorded invoices

- CHANGELOG.md
- src/Service/LeantimeApiService.php
- templates/planning/projects.html.twig
- templates/planning/users.html.twig
(https://leantime.itkdev.dk/#/tickets/showTicket/1270)
Changed data source for planning hours spent from "hoursRemaining" to "hoursLeft"
Added missing sum calculation in planning view twig
N/A
> 1270: Planning data hoursRemaining change

- CHANGELOG.md
- src/Service/DataSynchronizationService.php
<https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/1484>
Fixes cleanup of worklogs. Previously, the cleanup failed with the exception
>   [Doctrine\ORM\ORMInvalidArgumentException]
Detached entity App\Entity\Worklog@1022 cannot be removed
due to the [entity manager being cleared](https://github.com/itk-dev/economics/blob/2bd9d069cd182d367e301f1724877579dc49badc/src/Service/DataSynchronizationService.php#L125) during project worklog synchronization.
> 1484: Cleaned up worklog cleanup

- CHANGELOG.md
- migrations/Version20240621095459.php
- src/Controller/HourReportController.php
- src/Entity/Issue.php
- src/Form/HourReportType.php
- src/Model/Invoices/IssueData.php
- src/Model/Reports/HourReportFormData.php
- src/Model/Reports/HourReportWorklog.php
- src/Repository/IssueRepository.php
- src/Service/DataSynchronizationService.php
- src/Service/HourReportService.php
- src/Service/LeantimeApiService.php
- templates/reports/hour_report.html.twig
- templates/reports/reports.html.twig
- translations/messages.da.yaml
https://leantime.itkdev.dk/#/tickets/showTicket/1742
Simplified hour report form.
> Simplified hour report form

- CHANGELOG.md
- src/Enum/IssueStatusEnum.php
- src/Service/JiraApiService.php
- src/Service/LeantimeApiService.php
https://leantime.itkdev.dk/#/tickets/showTicket/2041
After discovering that Leantime issue status is defined per-project instead of being set in stone, the synchronization of leantime-issues needs to be adjusted.
N/A
> 2041: Revise leantime issue status sync

- CHANGELOG.md
- src/Service/HourReportService.php
https://leantime.itkdev.dk/#/tickets/showTicket/2050
After concluding that missing issue dueDate excludes relevant logs from the Hour Report, it has been decided to remove the issue duedate check from the logic.
N/A
> 2050: Hour-report issue duedate ignore

- CHANGELOG.md
- src/Form/HourReportType.php
https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/2096
The default dataprovider is already set in backend, but not in frontend. This PR serves to fix that.
> HourReport setting default data provider

- CHANGELOG.md
- assets/styles/app.css
- migrations/Version20241008053729.php
- src/Entity/Worklog.php
- templates/reports/reports.html.twig
https://leantime.itkdev.dk/dashboard/show#/tickets/showTicket/2663
Adding two indicies to the worklog table, improving the loading time of workload report from ~1 minute to ~2 seconds.
N/A
> 2663: Workload report speed optimization

- CHANGELOG.md
- reports.md
- src/Controller/ForecastReportController.php
- src/Form/ForecastReportType.php
- src/Model/Reports/ForecastReportData.php
- src/Model/Reports/ForecastReportFormData.php
- src/Model/Reports/ForecastReportIssueData.php
- src/Model/Reports/ForecastReportIssueVersionData.php
- src/Model/Reports/ForecastReportProjectData.php
- src/Model/Reports/ForecastReportWorklogData.php
- src/Repository/IssueRepository.php
- src/Repository/WorklogRepository.php
- src/Service/ForecastReportService.php
- templates/components/navigation.html.twig
- templates/reports/forecast_report.html.twig
- templates/reports/reports.html.twig
- translations/messages.da.yaml
[2617](https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=2617#/tickets/showTicket/2617)
A report showing invoiced versus recorded hours for projects specified
N/A
> 2617: Project forecast report

- CHANGELOG.md
- src/Service/HourReportService.php
N/A
When selecting a fromDate and toDate when configuring an Hour Report, the from and to dates should be included.
N/A
> hotfix: Correct from/to date check in hourreport

- CHANGELOG.md
- src/Command/MigrateEpicsCommand.php
- src/DataFixtures/AppFixtures.php
- src/Service/DataSynchronizationService.php
- tests/Service/DataSynchronizationServiceTest.php
[#2597](https://leantime.itkdev.dk/#/tickets/showTicket/2597)
Adds a command for migrating epics of existing/legacy issues to new entities. 
Should be fired once when the new changes are released in production.
N/A
> 2597-add-epic-migration-command

- CHANGELOG.md
- src/Controller/BillableUnbilledHoursReportController.php
- src/Form/BillableUnbilledHoursReportType.php
- src/Model/Reports/BillableUnbilledHoursReportData.php
- src/Model/Reports/BillableUnbilledHoursReportFormData.php
- src/Repository/WorklogRepository.php
- src/Service/BillableUnbilledHoursReportService.php
- src/Service/InvoicingRateReportService.php
- src/Service/WorkloadReportService.php
- templates/components/navigation.html.twig
- templates/reports/billable_unbilled_hours_report.html.twig
- translations/messages.da.yaml
[#3602](https://leantime.itkdev.dk/TimeTable/TimeTable?tab=ticketdetails#/tickets/showTicket/3602)
Added Billable unbilled hours report, for viewing billable worklogs that have not been billed.
N/A
> 3602: Billable unbilled hours report

- CHANGELOG.md
- src/Repository/WorklogRepository.php
- src/Service/DataSynchronizationService.php
https://leantime.itkdev.dk/#/tickets/showTicket/3602
Normally, unbilled worklogs should have isBilled set to false. Probably due to how values are set when logging time though Leantime Timetable, isBilled is unset and therefore evaluates to NULL when worklogs are synced.
Therefore, we need to explicitly set isBilled to 0 during sync.
N/A
> 3602: Explicitly define isBilled on worklogs

- CHANGELOG.md
- src/Repository/WorklogRepository.php
https://leantime.itkdev.dk/#/tickets/showTicket/3602
[#3602](https://github.com/itk-dev/economics/pull/214)
^ Turned out not to work as intended, as query used literals. This PR aims to solve this problem by defining the query values through parameters.
N/A
> hotfix: replaced literals with query params

- CHANGELOG.md
- src/Controller/BillableUnbilledHoursReportController.php
- src/Form/BillableUnbilledHoursReportType.php
- src/Model/Reports/BillableUnbilledHoursReportFormData.php
- src/Service/BillableUnbilledHoursReportService.php
- src/Service/DateTimeHelper.php
- src/Service/LeantimeApiService.php
- translations/messages.da.yaml
[#4282](https://leantime.itkdev.dk/#/tickets/showTicket/4282)
Adds the option to select a quarter to get the billable unbilled report for. It is possible to select no quarter, and get the report for the whole year.
> 4282: Quater picker for billable unbilled report
